### ISSUE TITLE
Building tascar on Ubuntu 18.10

### ISSUE THREAD

**Issue by m-r-s** [gisogrimm/tascar#10]
I had to do the following to make the build process complete on Ubuntu 18.10:

Checkout older version of labstreaminglayer:
`cd labstreaminglayer && git checkout 4c26a3b2863525e982786f57ac4a0cbf85ab965f`

Install additional packages:
`sudo apt install libgtksourceviewmm-3.0-dev g++-5`

Comment out line that builds documentation (line 6 in "Makefile")

Remove "openmha" from plugins list (in line 25 in "plugins/Makefile")

Build with older compiler version:
`CXX="g++-5" make`

**Comment by gisogrimm** [comment]
Only LTS versions of Ubuntu are supported.
