### ISSUE TITLE
Unable to render using command line interface

### ISSUE THREAD

**Issue by vpKumaravel** [gisogrimm/tascar#27]
Hello,

I have been trying to render a TASCAR session with audio input and save the output to a sound file. From the manual, I found the following command line.

`tascar_renderfile -i struwwelpeter-de_hoffman_64kb_trunc.wav -o output_audio.wav example_basic.tsc`

This, for some reasons do not work. I then found the following solution to be working:

`DYLD_LIBRARY_PATH="../tascar/libtascar/build" /usr/local/bin/tascar_renderfile -i struwwelpeter-de_hoffman_64kb_trunc.wav -o output_audio.wav example_basic.tsc`

However, I get the following error.

`Error: Unable to open source module "omni": dlopen(tascarsource_omni.dylib, 0x0002): tried: '../tascar/libtascar/build/tascarsource_omni.dylib' (no such file), 'tascarsource_omni.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OStascarsource_omni.dylib' (no such file), '/usr/lib/tascarsource_omni.dylib' (no such file, not in dyld cache), 'tascarsource_omni.dylib' (no such file)`

I use MacOS (Sonoma). 

Am I doing something wrong? Any help is appreciated.

Thanks,
Velu

**Comment by alastairhmoore** [comment]
It looks like a path issue. Did you get live sound processing working already?

I made some instructions with examples here:
https://github.com/alastairhmoore/tascar-on-mac-demos

**Comment by vpKumaravel** [comment]
> It looks like a path issue. Did you get live sound processing working already?
> 
> I made some instructions with examples here: https://github.com/alastairhmoore/tascar-on-mac-demos

Hello @alastairhmoore, thank you so much for your demo. I cleaned all my previous build and started from scratch using your Readme file. I am able to successfully load your first demo file in the TASCAR GUI. However, executing the CLI shows same error.

Apparently, it looks for the file tascarsource_omni.dylib on folders that do not contain it. Precisely, the lib files are in the folder `/usr/local/lib` but as you can see from the error message, it does not have it in the search list.

`Error: Unable to open source module "omni": dlopen(tascarsource_omni.dylib, 0x0002): tried: 'tascarsource_omni.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OStascarsource_omni.dylib' (no such file), '/usr/lib/tascarsource_omni.dylib' (no such file, not in dyld cache), 'tascarsource_omni.dylib' (no such file)`

`% find / -name "tascarsource_omni.dylib" `2>/dev/null`

`/usr/local/lib/tascarsource_omni.dylib`

What do you think is the solution? Should I manually move the contents from `/usr/local/lib` to `/usr/lib` such that it finds? Or is there a better way?

Thanks a lot,
Velu

**Comment by vpKumaravel** [comment]
Update:

I was able to fix it by changing the DYLD LIBRARY PATH to /usr/local/lib.

Thanks, again!
