### ISSUE TITLE
scene file path duplicated when reloading scenes opened via relative file paths 

### ISSUE THREAD

**Issue by gri573** [gisogrimm/tascar#29]
## observation
when reloading scenes that were loaded using `path/to/tascar.sh relative/path/to/file.tsc`, tascar throws the error
```
Error: While parsing file "relative/path/to/file.tsc": XML parser error (line 0, column 0): unable to open primary document entity '/absolute/path/to/working/directory/relative/path/to/relative/path/to/file.tsc'
```
reloading the scene again yields the same error, without further duplication in the file path.
## steps to reproduce
have tascar compiled and startable at `path/to/tascar.sh` and a tascar scene at `relative/path/to/file.tsc`, where `relative/path/to` contains at least one directory level.
launch tascar using  `path/to/tascar.sh relative/path/to/file.tsc`.
click on the `reload` button in the tascar GUI.

tested on commit 727a02ac1eb7234a401da53ac80d4d54c264bfa2

**Comment by gisogrimm** [comment]
Fixed by commit 54a79733a8e574cb9538034b029fa4dfe16290a8
