### ISSUE TITLE
Allow rendering when srv_port is set

### ISSUE THREAD

**Issue by fholzm** [gisogrimm/tascar#30]
If the srv_port attribute is set in the session element, it isn't possible to render audio files with `tascar_renderfile`:
```
Invalid attributes in element "session" (path /session): srv_port (valid attributes are: attribution duration initcmd initcmdsleep levelmeter_min levelmeter_mode levelmeter_range levelmeter_tc levelmeter_weight license loop playonload profilingpath requirefragsize requiresrate warnfragsize warnsrate).
```

**Comment by gisogrimm** [comment]
The message is actually only a warning and can be ignored. Anyhow this behaviour of displaying the "Invalid attributes" message is changed to silently ignore the attributes (commit 928e988).

The tools "tascar_renderfile" and "tascar_renderir" do not open an OSC server, thus setting the srv_port attribute has no effect there.
