### ISSUE TITLE
liblsl deb package generation fails on Ubuntu 18.10

### ISSUE THREAD

**Issue by m-r-s** [gisogrimm/tascar#9]
When following the instructions to build the deb package [1] on Ubuntu 18.10 I get the following error:

> [100%] Built target lsl
make[1]: Leaving directory '/home/marc/tascar/labstreaminglayer/LSL/liblsl/build'
make: Leaving directory '/home/marc/tascar/labstreaminglayer/LSL/liblsl/build'
cp: cannot stat '../../build/src/liblsl.so': No such file or directory
Architecture amd64 detected.
dpkg-deb: building package 'liblsl-dev' in 'debian.deb'.

The package liblsl is not built.

[1] https://github.com/gisogrimm/tascar/blob/bf67f96b911c56c1bf5f1e591c8c2f0583a00f9c/INSTALL#L46

**Comment by m-r-s** [comment]
The following change made the build succeed:

> diff --git a/LSL/liblsl/distros/deb/liblsl.csv b/LSL/liblsl/distros/deb/liblsl.csv
index 0cb3ffc9..e87ae70c 100644
--- a/LSL/liblsl/distros/deb/liblsl.csv
+++ b/LSL/liblsl/distros/deb/liblsl.csv
@@ -1,2 +1,2 @@
-"../../build/src/liblsl.so","usr/lib/"
+"../../build/liblsl64.so","usr/lib/"
 "../../LICENSE","usr/share/doc/liblsl/"

**Comment by m-r-s** [comment]
The compilation of still tascar fails with this workaround.
In the end I used an older version of labstreaminglayer, see #10.

**Comment by gisogrimm** [comment]
Only LTS versions of Ubuntu are supported.
